apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Artifact Traceability
on:
  workflow_dispatch:
jobs:
  register_build_artifacts:
    steps:
      - name: save-build-artifacts
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "myApp"
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: ""
